### ISSUE TITLE
Don't include your input data/puzzle

### ISSUE THREAD

**Issue by ben-nour** [MichielVanderhoydonck/aoc-python#1]
Hi!

Just a reminder not to share your input/data files! 

Advent of Code specifically requests you don't do this:

_**Can I copy/redistribute part of Advent of Code?** Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs. If you're making a website, please don't make it look like Advent of Code or name it something similar._

- [Advent of code](https://adventofcode.com/2024/about)

**Comment by MichielVanderhoydonck** [comment]
Hey Ben,

Apologies, I updated my repo and added a gitignore (fixed up and pushed so
it does not show in the commit history either).
Thanks for letting me know!

Kind regards,

Michiel
